### ISSUE TITLE
is `0.1.41` a test release?

### ISSUE THREAD

**Issue by chenrui333** [ucloud/ucloud-cli#65]
Asking because the release did not show in the changelog, also the version info in the repo did not get updated to `0.1.41`. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/116903

**Comment by fioncat** [comment]
Thanks for feedback, we had problem releasing `0.1.41` yesterday, now it is fixed.
Should I create a new PR to homebrew-core or use this old one ?

**Comment by chenrui333** [comment]
yeah, we can just that one. Should be fine.

**Comment by chenrui333** [comment]
@fioncat I think you missed one version info update, just raised #66 for the issue.

**Comment by chenrui333** [comment]
And you probably need another re-tag

**Comment by fioncat** [comment]
Okay, sorry, we forgot this 😂
I will re-tag one.
